// Auto-generated shared legal content (source: CraftWise_Legal_Texts_Website_Update_2026-06-17.docx).
// German versions are the legally leading texts; English versions are translations.
// Consumed by the seed script (scripts/seed-legal-documents.mjs) and by the static
// fallbacks in each legal page when the database has no published version.

export const LEGAL_CONTENT = [
  {
    key: "PRIVACY_POLICY",
    locale: "de",
    title: "Datenschutzerklärung",
    metaTitle: "Datenschutzerklärung | CraftWise",
    metaDescription: "Wie die CraftWise GmbH personenbezogene Daten verarbeitet, wenn du unsere Website besuchst, mit uns Kontakt aufnimmst oder CraftWise nutzt.",
    heroTitle: "Datenschutzerklärung",
    heroSemiTitle: "Stand: 17. Juni 2026",
    heroDescription: "Diese Datenschutzerklärung informiert darüber, wie die CraftWise GmbH personenbezogene Daten verarbeitet, wenn du unsere Website besuchst, mit uns Kontakt aufnimmst oder unsere Software-as-a-Service-Plattform CraftWise nutzt.",
    heroImage: "/images/thumbs/privacy-policy.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Verantwortlicher</h2><p>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Deutschland<br/>E-Mail: support@craft-wise.de</p></div>
        <div class="legal-section"><h2>2. Zielgruppe und Rollen nach der DSGVO</h2><p>CraftWise richtet sich ausschließlich an Unternehmer im Sinne von § 14 BGB.</p><p>Soweit wir personenbezogene Daten im Zusammenhang mit dem Besuch unserer Website, der Vertragsanbahnung, Vertragsverwaltung, Abrechnung, Supportkommunikation oder eigenen Marketingmaßnahmen verarbeiten, sind wir Verantwortlicher im Sinne von Art. 4 Nr. 7 DSGVO.</p><p>Soweit Kunden personenbezogene Daten ihrer Mitarbeiter, Ansprechpartner, Projektbeteiligten, Subunternehmer oder sonstiger Personen innerhalb der CraftWise Plattform verarbeiten, handelt der jeweilige Kunde grundsätzlich als Verantwortlicher. CraftWise verarbeitet diese Daten als Auftragsverarbeiter nach Art. 28 DSGVO auf Grundlage eines gesonderten Auftragsverarbeitungsvertrags.</p></div>
        <div class="legal-section"><h2>3. Verarbeitete Datenkategorien</h2><p><strong>Wir können insbesondere folgende Daten verarbeiten:</strong></p><ul><li>Stammdaten: Name, Firmenname, Anschrift, Kontaktdaten, Unternehmensdaten.</li><li>Vertragsdaten: gebuchter Tarif, Vertragsbeginn, Vertragslaufzeit, Lizenz- und Nutzerinformationen.</li><li>Zahlungs- und Abrechnungsdaten: Rechnungsadresse, Zahlungsstatus, Zahlungsereignisse und erforderliche Zahlungsinformationen, soweit diese für die Abwicklung über Zahlungsdienstleister erforderlich sind.</li><li>Nutzungs- und Sicherheitsdaten: Logins, technische Kennungen, IP-Adressen, Geräte- und Browserinformationen, Fehlerprotokolle, Sicherheitsereignisse.</li><li>Kommunikationsdaten: E-Mails, Supportanfragen, Chat- oder Formularinhalte.</li><li>Plattformdaten des Kunden: Projektinformationen, Aufgaben, Termine, Zeiterfassungen, Dokumente, Angebots- und Rechnungsdaten, Chatnachrichten und sonstige vom Kunden eingegebene Inhalte.</li><li>Marketingdaten: E-Mail-Adresse, Einwilligungsstatus, Zeitpunkt der Anmeldung und Abmeldung, sofern du dich für Newsletter, Produktinformationen oder ein Referral-Programm registrierst.</li></ul><p>Besondere Kategorien personenbezogener Daten im Sinne von Art. 9 DSGVO sind nicht Zweck der Plattform. Kunden sind dafür verantwortlich, solche Daten nicht oder nur dann einzugeben, wenn hierfür eine zulässige Rechtsgrundlage besteht. Angaben zu Abwesenheiten oder Krankheitstagen sollten ohne Diagnosen oder medizinische Details erfolgen.</p></div>
        <div class="legal-section"><h2>4. Zwecke und Rechtsgrundlagen</h2><p>Wir verarbeiten personenbezogene Daten nur, soweit dies erforderlich und rechtlich zulässig ist. Je nach Verarbeitung gelten insbesondere folgende Rechtsgrundlagen:</p><ul><li><strong>Art. 6 Abs. 1 lit. b DSGVO:</strong> Vertragserfüllung und vorvertragliche Maßnahmen, z. B. Bereitstellung der Software, Kundenverwaltung, Support, Abrechnung.</li><li><strong>Art. 6 Abs. 1 lit. c DSGVO:</strong> Erfüllung gesetzlicher Pflichten, z. B. handels- und steuerrechtliche Aufbewahrungspflichten.</li><li><strong>Art. 6 Abs. 1 lit. f DSGVO:</strong> berechtigte Interessen, z. B. IT-Sicherheit, Missbrauchsprävention, Fehleranalyse, Weiterentwicklung unserer Dienste, Durchsetzung oder Abwehr rechtlicher Ansprüche.</li><li><strong>Art. 6 Abs. 1 lit. a DSGVO:</strong> Einwilligung, z. B. bei nicht erforderlichen Cookies, Analyse-Tools, Newsletter, bestimmten Marketingmaßnahmen oder optionalen Integrationen, soweit hierfür eine Einwilligung erforderlich ist.</li><li><strong>Art. 28 DSGVO:</strong> Auftragsverarbeitung, soweit CraftWise personenbezogene Daten im Auftrag des Kunden innerhalb der Plattform verarbeitet.</li></ul></div>
        <div class="legal-section"><h2>5. Website, Hosting und technische Bereitstellung</h2><p>Unsere öffentliche Website wird bei Hostinger gehostet. Anbieter ist Hostinger International Ltd., 61 Lordou Vironos Street, 6023 Larnaca, Zypern, bzw. ein mit Hostinger verbundenes Unternehmen oder ein von Hostinger eingesetzter Rechenzentrums- bzw. Infrastrukturpartner.</p><p>Beim Besuch der Website werden technisch erforderliche Daten verarbeitet, insbesondere IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seiten, Browser- und Geräteinformationen, Referrer-URL und Server-Logdaten. Die Verarbeitung erfolgt zur sicheren und stabilen Bereitstellung der Website, zur Fehleranalyse und zur Abwehr von Angriffen auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p><p>Mit Hostinger besteht, soweit erforderlich, ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO. Wenn Hostinger oder eingesetzte Unterauftragnehmer Daten außerhalb des Europäischen Wirtschaftsraums verarbeiten, erfolgt dies nur auf Grundlage geeigneter Garantien, insbesondere EU-Standardvertragsklauseln und ergänzender Schutzmaßnahmen.</p><p>Die CraftWise App und die damit verbundenen Kernfunktionen werden getrennt von der öffentlichen Website betrieben. Die App nutzt insbesondere Firebase bzw. Google Cloud Dienste in EU-Regionen, soweit dies für die jeweilige Funktion verfügbar und konfiguriert ist.</p></div>
        <div class="legal-section"><h2>6. Cookies, Einwilligungsmanagement und Analyse</h2><p>Unsere Website verwendet technisch erforderliche Cookies und vergleichbare Technologien, die für den Betrieb der Website, Sicherheit, Spracheinstellungen oder die Anzeige des Cookie-Banners notwendig sind. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p><p>Nicht erforderliche Cookies, Analyse-Tools oder Marketing-Technologien verwenden wir nur, wenn du vorher eingewilligt hast. Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO. Du kannst eine erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Sofern Google Analytics oder vergleichbare Analyse-Tools eingesetzt werden, erfolgt dies nur mit Einwilligung, mit angemessenen Datenschutzkonfigurationen, insbesondere IP-Anonymisierung bzw. IP-Masking, und auf Grundlage der jeweils erforderlichen Verträge und Transfermechanismen.</p></div>
        <div class="legal-section"><h2>7. Kontaktaufnahme und Support</h2><p>Wenn du uns per E-Mail, Kontaktformular, Chat oder über andere Kommunikationswege kontaktierst, verarbeiten wir die von dir übermittelten Daten zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Anfrage mit einem Vertrag oder vorvertraglichen Maßnahmen zusammenhängt, und im Übrigen Art. 6 Abs. 1 lit. f DSGVO.</p><p>Supportanfragen können Informationen über dein Unternehmen, deinen Account, technische Fehler oder von dir bereitgestellte Inhalte enthalten. Bitte übermittle uns keine sensiblen Daten, soweit dies für die Bearbeitung nicht erforderlich ist.</p></div>
        <div class="legal-section"><h2>8. Registrierung, Testphase und Nutzung der CraftWise Plattform</h2><p>Bei Registrierung und Nutzung der Plattform verarbeiten wir Daten, die zur Einrichtung, Verwaltung und Bereitstellung deines Accounts erforderlich sind. Dazu gehören insbesondere Unternehmensdaten, Kontaktdaten, Login-Daten, Rollen, Lizenzinformationen, Nutzungsdaten und technische Sicherheitsdaten.</p><p>Die Verarbeitung erfolgt zur Bereitstellung der Plattform, zur Vertragsdurchführung, zur Sicherheit des Dienstes, zur Fehlerbehebung und zur Weiterentwicklung der Software. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und lit. f DSGVO. Soweit wir Daten im Auftrag des Kunden verarbeiten, gilt ergänzend der Auftragsverarbeitungsvertrag.</p></div>
        <div class="legal-section"><h2>9. Zahlungsabwicklung</h2><p>Für die Zahlungsabwicklung können wir Stripe Payments Europe, Limited, 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland, einsetzen. Stripe verarbeitet Zahlungsdaten zur Durchführung von Zahlungen, Betrugsprävention, Compliance und Abrechnung. Je nach konkretem Verarbeitungsvorgang kann Stripe als Auftragsverarbeiter oder eigener Verantwortlicher handeln.</p><p>Wir erhalten nicht alle vollständigen Zahlungsdaten, insbesondere keine vollständigen Kreditkartendaten. Diese werden regelmäßig direkt durch den Zahlungsdienstleister verarbeitet. Details ergeben sich aus den Datenschutzhinweisen von Stripe.</p></div>
        <div class="legal-section"><h2>10. Newsletter, Produktinformationen und Referral-Programm</h2><p>Newsletter und werbliche Produktinformationen versenden wir nur mit Einwilligung oder, soweit gesetzlich zulässig, im Rahmen bestehender Kundenbeziehungen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 6 Abs. 1 lit. f DSGVO in Verbindung mit den einschlägigen wettbewerbsrechtlichen Vorgaben.</p><p>Du kannst Newsletter und werbliche Mitteilungen jederzeit abbestellen. Für den Nachweis der Einwilligung speichern wir Anmeldezeitpunkt, Bestätigung, IP-Adresse und Abmeldestatus, soweit erforderlich.</p><p>Wenn du an einem Referral-Programm teilnimmst, verarbeiten wir die dafür erforderlichen Daten, insbesondere Empfehlungslinks, Zuordnung zwischen werbendem Kunden und Neukunden, Rabattstatus und Abrechnungsinformationen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit das Programm Bestandteil eines Vertrags ist, und im Übrigen Art. 6 Abs. 1 lit. f DSGVO.</p></div>
        <div class="legal-section"><h2>11. Optionale Integrationen und Schnittstellen</h2><p>CraftWise kann optionale Integrationen anbieten, z. B. für Kalender- und Meeting-Dienste, Zahlungs- und Buchhaltungsdienste oder den Export von Rechnungs- und Projektdaten. Dazu können insbesondere Microsoft 365 / Outlook / Teams, Google Calendar / Google Meet, Zoom, DATEV, sevdesk, lexoffice, Stripe oder vergleichbare Dienste gehören.</p><p>Integrationen werden nur aktiviert, wenn der Kunde oder ein berechtigter Nutzer dies veranlasst. Je nach Integration können personenbezogene Daten an den jeweiligen Anbieter übertragen werden, z. B. Name, E-Mail-Adresse, Kalenderinformationen, Meetingdaten, Rechnungsdaten oder technische Metadaten. Verantwortlich für die Auswahl, Aktivierung, Konfiguration und rechtliche Zulässigkeit der Integration ist grundsätzlich der Kunde.</p><p>Soweit CraftWise eine Integration technisch bereitstellt und dabei personenbezogene Daten im Auftrag des Kunden verarbeitet, erfolgt dies auf Grundlage des Auftragsverarbeitungsvertrags. Soweit Drittanbieter eigene Zwecke verfolgen, gelten ergänzend deren eigene Datenschutzinformationen.</p></div>
        <div class="legal-section"><h2>12. Social Media und externe Links</h2><p>Unsere Website kann Links zu Profilen oder Seiten von CraftWise bei externen Plattformen wie LinkedIn, Instagram, Facebook, YouTube, TikTok oder WhatsApp enthalten. Wenn du diese Links anklickst, verlässt du unsere Website. Für die Verarbeitung personenbezogener Daten auf den jeweiligen Plattformen sind grundsätzlich die jeweiligen Anbieter verantwortlich.</p><p>Soweit Inhalte externer Plattformen direkt auf unserer Website eingebunden werden, erfolgt dies nur mit entsprechender Einwilligung, sofern hierfür personenbezogene Daten an den Drittanbieter übertragen werden.</p></div>
        <div class="legal-section"><h2>13. Empfänger und Dienstleister</h2><p>Wir geben personenbezogene Daten nur weiter, wenn dies zur Bereitstellung unserer Leistungen erforderlich ist, eine rechtliche Verpflichtung besteht, du eingewilligt hast oder eine andere Rechtsgrundlage dies erlaubt.</p><p><strong>Zu den Empfängern können insbesondere gehören:</strong></p><ul><li>Hosting- und Infrastruktur-Anbieter, insbesondere Hostinger für die öffentliche Website sowie Google Ireland Limited / Firebase / Google Cloud für App-Hosting, Authentifizierung, Datenbank, Storage und technische Plattformdienste.</li><li>Zahlungsdienstleister, insbesondere Stripe.</li><li>Kommunikations-, Support- und E-Mail-Dienstleister.</li><li>Anbieter optionaler Integrationen, sofern diese vom Kunden aktiviert werden.</li><li>Steuerberater, Rechtsberater, Behörden oder Gerichte, soweit dies erforderlich oder gesetzlich vorgeschrieben ist.</li></ul><p>Mit Auftragsverarbeitern schließen wir, soweit erforderlich, Verträge nach Art. 28 DSGVO.</p></div>
        <div class="legal-section"><h2>14. Internationale Datenübermittlungen</h2><p>Wir streben eine Verarbeitung innerhalb der Europäischen Union bzw. des Europäischen Wirtschaftsraums an. Dennoch kann es bei bestimmten Dienstleistern, Supportleistungen, globalen Infrastrukturdiensten, Push-Benachrichtigungen oder optionalen Integrationen zu einer Übermittlung in Drittländer kommen.</p><p>Eine Drittlandübermittlung erfolgt nur, wenn hierfür eine Rechtsgrundlage besteht, insbesondere ein Angemessenheitsbeschluss der EU-Kommission, EU-Standardvertragsklauseln, ergänzende Schutzmaßnahmen oder eine gesetzliche Ausnahme nach Art. 49 DSGVO.</p></div>
        <div class="legal-section"><h2>15. Speicherdauer und Löschung</h2><p>Wir speichern personenbezogene Daten nur so lange, wie dies für die jeweiligen Zwecke erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen.</p><p>Vertrags-, Zahlungs- und steuerlich relevante Daten können aufgrund handels- und steuerrechtlicher Pflichten regelmäßig für bis zu zehn Jahre gespeichert werden. Support- und Kommunikationsdaten werden gelöscht, sobald sie für die Bearbeitung nicht mehr erforderlich sind, sofern keine gesetzlichen Aufbewahrungspflichten oder berechtigten Interessen entgegenstehen.</p><p>Kundendaten innerhalb der Plattform werden nach Vertragsende gemäß dem Auftragsverarbeitungsvertrag gelöscht oder anonymisiert, soweit keine gesetzlichen Pflichten oder berechtigten Gründe für eine weitere Speicherung bestehen. Daten in Backups werden im Rahmen regulärer Backup-Zyklen überschrieben und bis dahin angemessen geschützt.</p></div>
        <div class="legal-section"><h2>16. Datensicherheit</h2><p>Wir setzen angemessene technische und organisatorische Maßnahmen ein, um personenbezogene Daten gegen Verlust, Missbrauch, unbefugten Zugriff, Offenlegung, Veränderung oder Zerstörung zu schützen. Dazu gehören insbesondere TLS-Verschlüsselung, rollenbasierte Zugriffsrechte, Zugriffsbeschränkungen, Protokollierung sicherheitsrelevanter Ereignisse, Backup- und Wiederherstellungsprozesse sowie organisatorische Vertraulichkeitsmaßnahmen.</p></div>
        <div class="legal-section"><h2>17. Deine Rechte</h2><p><strong>Du hast nach Maßgabe der DSGVO insbesondere folgende Rechte:</strong></p><ul><li>Recht auf Auskunft nach Art. 15 DSGVO.</li><li>Recht auf Berichtigung nach Art. 16 DSGVO.</li><li>Recht auf Löschung nach Art. 17 DSGVO.</li><li>Recht auf Einschränkung der Verarbeitung nach Art. 18 DSGVO.</li><li>Recht auf Datenübertragbarkeit nach Art. 20 DSGVO.</li><li>Recht auf Widerspruch nach Art. 21 DSGVO.</li><li>Recht auf Widerruf einer Einwilligung nach Art. 7 Abs. 3 DSGVO.</li><li>Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde nach Art. 77 DSGVO.</li></ul><p>Wenn CraftWise Daten im Auftrag eines Kunden verarbeitet, sollte die Anfrage grundsätzlich an den jeweiligen Kunden als Verantwortlichen gerichtet werden. Du kannst dich dennoch an uns wenden; wir leiten die Anfrage soweit möglich an den zuständigen Kunden weiter.</p></div>
        <div class="legal-section"><h2>18. Zuständige Aufsichtsbehörde</h2><p>Du kannst dich bei jeder zuständigen Datenschutzaufsichtsbehörde beschweren. Für die CraftWise GmbH ist insbesondere zuständig:</p><p>Der Hessische Beauftragte für Datenschutz und Informationsfreiheit<br/>Postfach 3163<br/>65021 Wiesbaden<br/>Deutschland</p></div>
        <div class="legal-section"><h2>19. Änderungen dieser Datenschutzerklärung</h2><p>Wir können diese Datenschutzerklärung anpassen, wenn sich unsere Verarbeitungsvorgänge, eingesetzte Dienstleister, rechtliche Anforderungen oder technische Funktionen ändern. Die jeweils aktuelle Fassung ist auf unserer Website abrufbar.</p></div>
      `,
  },
  {
    key: "PRIVACY_POLICY",
    locale: "en",
    title: "Privacy Policy",
    metaTitle: "Privacy Policy | CraftWise",
    metaDescription: "This Privacy Policy explains how CraftWise GmbH processes personal data when you visit our website, contact us or use the CraftWise software-as-a-service platform.",
    heroTitle: "Privacy Policy",
    heroSemiTitle: "Last updated: 17 June 2026",
    heroDescription: "This Privacy Policy explains how CraftWise GmbH processes personal data when you visit our website, contact us or use the CraftWise software-as-a-service platform.",
    heroImage: "/images/thumbs/privacy-policy.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Controller</h2><p>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Germany<br/>Email: support@craft-wise.de</p></div>
        <div class="legal-section"><h2>2. Target group and GDPR roles</h2><p>CraftWise is intended exclusively for business customers.</p><p>Where we process personal data in connection with our website, contract initiation, contract administration, billing, support communication or our own marketing activities, CraftWise acts as controller within the meaning of Art. 4(7) GDPR.</p><p>Where customers process personal data of their employees, contacts, project participants, subcontractors or other persons within the CraftWise platform, the respective customer generally acts as controller. CraftWise processes such data as processor under Art. 28 GDPR on the basis of a separate Data Processing Agreement.</p></div>
        <div class="legal-section"><h2>3. Categories of data processed</h2><p><strong>We may process in particular the following categories of data:</strong></p><ul><li>Master data: name, company name, address, contact details and company information.</li><li>Contract data: selected plan, contract start, contract term, licence and user information.</li><li>Payment and billing data: billing address, payment status, payment events and payment information required for processing through payment service providers.</li><li>Usage and security data: logins, technical identifiers, IP addresses, device and browser information, error logs and security events.</li><li>Communication data: emails, support requests, chat or form content.</li><li>Customer platform data: project information, tasks, appointments, time tracking, documents, quote and invoice data, chat messages and other content entered by the customer.</li><li>Marketing data: email address, consent status, sign-up and unsubscribe timestamps where you register for newsletters, product information or referral programmes.</li></ul><p>Special categories of personal data within the meaning of Art. 9 GDPR are not intended to be processed through the platform. Customers are responsible for ensuring that such data is not entered unless a valid legal basis exists. Absence or sickness information should be entered without diagnoses or medical details.</p></div>
        <div class="legal-section"><h2>4. Purposes and legal bases</h2><p>We process personal data only where required and legally permitted. Depending on the processing activity, the following legal bases apply in particular:</p><ul><li><strong>Art. 6(1)(b) GDPR:</strong> performance of a contract and pre-contractual measures, e.g. provision of the software, customer administration, support and billing.</li><li><strong>Art. 6(1)(c) GDPR:</strong> compliance with legal obligations, e.g. commercial and tax retention obligations.</li><li><strong>Art. 6(1)(f) GDPR:</strong> legitimate interests, e.g. IT security, abuse prevention, error analysis, service improvement and establishment, exercise or defence of legal claims.</li><li><strong>Art. 6(1)(a) GDPR:</strong> consent, e.g. for non-essential cookies, analytics tools, newsletters, certain marketing activities or optional integrations where consent is required.</li><li><strong>Art. 28 GDPR:</strong> processing on behalf of customers where CraftWise processes personal data within the platform as processor.</li></ul></div>
        <div class="legal-section"><h2>5. Website, hosting and technical delivery</h2><p>Our public website is hosted by Hostinger. The provider is Hostinger International Ltd., 61 Lordou Vironos Street, 6023 Larnaca, Cyprus, or an affiliated Hostinger entity or data centre/infrastructure partner used by Hostinger.</p><p>When you visit the website, technically necessary data is processed, in particular IP address, date and time of access, pages accessed, browser and device information, referrer URL and server log data. This processing is carried out to provide the website securely and reliably, analyse errors and defend against attacks on the basis of Art. 6(1)(f) GDPR.</p><p>Where required, we have entered into a Data Processing Agreement with Hostinger pursuant to Art. 28 GDPR. If Hostinger or its subprocessors process data outside the European Economic Area, this is done only on the basis of appropriate safeguards, in particular EU Standard Contractual Clauses and supplementary measures.</p><p>The CraftWise app and its core functions are operated separately from the public website. The app uses in particular Firebase and Google Cloud services in EU regions where available and configured for the respective function.</p></div>
        <div class="legal-section"><h2>6. Cookies, consent management and analytics</h2><p>Our website uses technically necessary cookies and similar technologies required for website operation, security, language settings or display of the cookie banner. The legal basis is Art. 6(1)(f) GDPR.</p><p>We use non-essential cookies, analytics tools or marketing technologies only if you have given prior consent. The legal basis is Art. 6(1)(a) GDPR. You may withdraw consent at any time with effect for the future.</p><p>If Google Analytics or comparable analytics tools are used, this is done only with consent, appropriate privacy settings, in particular IP anonymisation or IP masking, and on the basis of the required agreements and transfer mechanisms.</p></div>
        <div class="legal-section"><h2>7. Contact and support</h2><p>If you contact us by email, contact form, chat or other means, we process the data you provide to handle your request. The legal basis is Art. 6(1)(b) GDPR where the request relates to a contract or pre-contractual measures, and otherwise Art. 6(1)(f) GDPR.</p><p>Support requests may contain information about your company, account, technical errors or content provided by you. Please do not send sensitive data unless necessary for handling the request.</p></div>
        <div class="legal-section"><h2>8. Registration, trial and use of the CraftWise platform</h2><p>When you register for and use the platform, we process data required to set up, manage and provide your account. This includes company data, contact details, login data, roles, licence information, usage data and technical security data.</p><p>Processing is carried out to provide the platform, perform the contract, secure the service, resolve errors and improve the software. The legal bases are Art. 6(1)(b) and Art. 6(1)(f) GDPR. Where we process data on behalf of the customer, the Data Processing Agreement applies in addition.</p></div>
        <div class="legal-section"><h2>9. Payment processing</h2><p>We may use Stripe Payments Europe, Limited, 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Ireland, for payment processing. Stripe processes payment data for payment execution, fraud prevention, compliance and billing. Depending on the processing activity, Stripe may act as processor or independent controller.</p><p>We do not receive all complete payment data, in particular no full credit card details. These are generally processed directly by the payment service provider. Details are provided in Stripe’s privacy information.</p></div>
        <div class="legal-section"><h2>10. Newsletter, product information and referral programme</h2><p>We send newsletters and promotional product information only with consent or, where legally permitted, within existing customer relationships. The legal basis is Art. 6(1)(a) GDPR or Art. 6(1)(f) GDPR in conjunction with applicable marketing law.</p><p>You may unsubscribe from newsletters and promotional communications at any time. To prove consent, we store sign-up time, confirmation, IP address and unsubscribe status where necessary.</p><p>If you participate in a referral programme, we process the required data, in particular referral links, allocation between referring customer and new customer, discount status and billing information. The legal basis is Art. 6(1)(b) GDPR where the programme is part of a contract and otherwise Art. 6(1)(f) GDPR.</p></div>
        <div class="legal-section"><h2>11. Optional integrations and interfaces</h2><p>CraftWise may offer optional integrations, e.g. for calendar and meeting services, payment and accounting services or exports of invoice and project data. These may include Microsoft 365 / Outlook / Teams, Google Calendar / Google Meet, Zoom, DATEV, sevdesk, lexoffice, Stripe or comparable services.</p><p>Integrations are activated only if the customer or an authorised user initiates this. Depending on the integration, personal data may be transmitted to the relevant provider, e.g. name, email address, calendar information, meeting data, invoice data or technical metadata. The customer is generally responsible for selecting, activating, configuring and ensuring the legal permissibility of the integration.</p><p>Where CraftWise technically provides an integration and processes personal data on behalf of the customer, this is done on the basis of the Data Processing Agreement. Where third-party providers pursue their own purposes, their own privacy information applies in addition.</p></div>
        <div class="legal-section"><h2>12. Social media and external links</h2><p>Our website may contain links to CraftWise profiles or pages on external platforms such as LinkedIn, Instagram, Facebook, YouTube, TikTok or WhatsApp. If you click these links, you leave our website. The respective providers are generally responsible for processing personal data on those platforms.</p><p>Where content from external platforms is embedded directly on our website, this is done only with appropriate consent if personal data is transmitted to the third-party provider.</p></div>
        <div class="legal-section"><h2>13. Recipients and service providers</h2><p>We disclose personal data only where necessary to provide our services, where a legal obligation exists, where you have consented or where another legal basis permits disclosure.</p><p><strong>Recipients may include in particular:</strong></p><ul><li>Hosting and infrastructure providers, in particular Hostinger for the public website and Google Ireland Limited / Firebase / Google Cloud for app hosting, authentication, database, storage and technical platform services.</li><li>Payment service providers, in particular Stripe.</li><li>Communication, support and email service providers.</li><li>Providers of optional integrations where activated by the customer.</li><li>Tax advisors, legal advisors, authorities or courts where required or legally prescribed.</li></ul><p>Where required, we enter into Data Processing Agreements with processors pursuant to Art. 28 GDPR.</p></div>
        <div class="legal-section"><h2>14. International transfers</h2><p>We aim to process data within the European Union or the European Economic Area. Nevertheless, certain service providers, support activities, global infrastructure services, push notifications or optional integrations may involve transfers to third countries.</p><p>Transfers to third countries take place only where a legal basis exists, in particular an adequacy decision of the European Commission, EU Standard Contractual Clauses, supplementary safeguards or a statutory exception under Art. 49 GDPR.</p></div>
        <div class="legal-section"><h2>15. Retention and deletion</h2><p>We store personal data only as long as necessary for the relevant purposes or as required by statutory retention obligations.</p><p>Contract, payment and tax-relevant data may generally be stored for up to ten years due to commercial and tax law obligations. Support and communication data is deleted once it is no longer required for handling the matter, unless statutory retention obligations or legitimate interests prevent deletion.</p><p>Customer data within the platform is deleted or anonymised after contract termination in accordance with the Data Processing Agreement, unless legal obligations or legitimate reasons require further storage. Backup data is overwritten within regular backup cycles and protected appropriately until deletion.</p></div>
        <div class="legal-section"><h2>16. Data security</h2><p>We use appropriate technical and organisational measures to protect personal data against loss, misuse, unauthorised access, disclosure, alteration or destruction. These include TLS encryption, role-based access controls, access restrictions, logging of security-relevant events, backup and recovery processes and organisational confidentiality measures.</p></div>
        <div class="legal-section"><h2>17. Your rights</h2><p>Subject to the GDPR requirements, you have in particular the following rights:</p><ul><li>Right of access under Art. 15 GDPR.</li><li>Right to rectification under Art. 16 GDPR.</li><li>Right to erasure under Art. 17 GDPR.</li><li>Right to restriction of processing under Art. 18 GDPR.</li><li>Right to data portability under Art. 20 GDPR.</li><li>Right to object under Art. 21 GDPR.</li><li>Right to withdraw consent under Art. 7(3) GDPR.</li><li>Right to lodge a complaint with a data protection supervisory authority under Art. 77 GDPR.</li></ul><p>Where CraftWise processes data on behalf of a customer, requests should generally be addressed to the respective customer as controller. You may still contact us; we will forward the request to the responsible customer where possible.</p></div>
        <div class="legal-section"><h2>18. Supervisory authority</h2><p>You may lodge a complaint with any competent data protection supervisory authority. For CraftWise GmbH, the competent authority is in particular:</p><p>The Hessian Commissioner for Data Protection and Freedom of Information<br/>Postfach 3163<br/>65021 Wiesbaden<br/>Germany</p></div>
        <div class="legal-section"><h2>19. Changes to this Privacy Policy</h2><p>We may update this Privacy Policy if our processing activities, service providers, legal requirements or technical functions change. The current version is available on our website.</p></div>
      `,
  },
  {
    key: "TERMS_CONDITIONS",
    locale: "de",
    title: "Allgemeine Geschäftsbedingungen (AGB)",
    metaTitle: "Allgemeine Geschäftsbedingungen (AGB) | CraftWise",
    metaDescription: "Die vertraglichen Bedingungen für die Nutzung der CraftWise SaaS-Plattform und zugehöriger Leistungen.",
    heroTitle: "Allgemeine Geschäftsbedingungen (AGB)",
    heroSemiTitle: "Stand: 17. Juni 2026",
    heroDescription: "Die vertraglichen Bedingungen für die Nutzung der CraftWise SaaS-Plattform und zugehöriger Leistungen.",
    heroImage: "/images/thumbs/terms.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Geltung und Vertragspartner</h2><p>Diese Allgemeinen Geschäftsbedingungen regeln das Vertragsverhältnis zwischen der CraftWise GmbH, Ulmenweg 12, 64331 Weiterstadt, Deutschland (“CraftWise”), und ihren Kunden.</p><p>CraftWise erbringt Leistungen ausschließlich gegenüber Unternehmern im Sinne von § 14 BGB. Verbraucher im Sinne von § 13 BGB sind nicht zum Vertragsschluss berechtigt.</p><p>Abweichende, entgegenstehende oder ergänzende Geschäftsbedingungen des Kunden werden nicht Vertragsbestandteil, es sei denn, CraftWise stimmt ihrer Geltung ausdrücklich in Textform zu.</p></div>
        <div class="legal-section"><h2>2. Leistungen von CraftWise</h2><p>CraftWise stellt eine Software-as-a-Service-Lösung für Handwerks- und projektorientierte Betriebe bereit. Die Software kann insbesondere Funktionen für Projektmanagement, Aufgaben, Termine, Zeiterfassung, Dokumentenverwaltung, Kommunikation, Angebots- und Rechnungswesen sowie mobile Nutzung umfassen.</p><p>Der konkrete Funktionsumfang ergibt sich aus dem jeweils gebuchten Tarif, der Leistungsbeschreibung auf der Website, dem Angebot oder einer gesonderten Vereinbarung. Individuelle Anpassungen, Integrationen, Schulungen oder Beratungsleistungen schuldet CraftWise nur, wenn diese ausdrücklich vereinbart wurden.</p><p>CraftWise darf die Software weiterentwickeln, aktualisieren und an technische, rechtliche oder wirtschaftliche Anforderungen anpassen, sofern der vertraglich vereinbarte Kernnutzen nicht wesentlich beeinträchtigt wird.</p></div>
        <div class="legal-section"><h2>3. Registrierung, Account und Nutzungsberechtigung</h2><p>Der Kunde ist verpflichtet, bei Registrierung und Vertragsabschluss vollständige und richtige Angaben zu machen und diese aktuell zu halten.</p><p>Der Kunde ist für alle Aktivitäten verantwortlich, die über seinen Account oder die von ihm angelegten Nutzerkonten erfolgen. Zugangsdaten sind vertraulich zu behandeln und vor Zugriffen Dritter zu schützen.</p><p>Der Kunde stellt sicher, dass nur berechtigte Personen die Software nutzen und dass Nutzerrollen und Berechtigungen sachgerecht vergeben werden.</p></div>
        <div class="legal-section"><h2>4. Nutzungsrechte</h2><p>CraftWise räumt dem Kunden für die Dauer des Vertrags ein einfaches, nicht ausschließliches, nicht übertragbares und nicht unterlizenzierbares Recht ein, die Software im vereinbarten Umfang für eigene geschäftliche Zwecke zu nutzen.</p><p>Eine Überlassung der Software an Dritte, ein Weiterverkauf, Reverse Engineering, Umgehung technischer Schutzmaßnahmen, missbräuchliche Nutzung oder Nutzung außerhalb des vereinbarten Umfangs ist untersagt, soweit dies nicht gesetzlich zwingend erlaubt ist.</p></div>
        <div class="legal-section"><h2>5. Verfügbarkeit, Wartung und Support</h2><p>CraftWise bemüht sich um eine hohe Verfügbarkeit der Software. Eine bestimmte Verfügbarkeit oder unterbrechungsfreie Nutzbarkeit ist jedoch nur geschuldet, wenn dies ausdrücklich vereinbart wurde.</p><p>Vorübergehende Einschränkungen können insbesondere durch Wartung, Updates, Sicherheitsmaßnahmen, Störungen von Drittanbietern, höhere Gewalt, Internetstörungen oder Ereignisse entstehen, die außerhalb des Einflussbereichs von CraftWise liegen.</p><p>Support wird während üblicher Geschäftszeiten über die von CraftWise angebotenen Supportkanäle erbracht, insbesondere per E-Mail oder innerhalb der Plattform. Reaktionszeiten sind nur verbindlich, wenn sie ausdrücklich vereinbart wurden.</p></div>
        <div class="legal-section"><h2>6. Preise, Abrechnung und Zahlung</h2><p>Es gelten die zum Zeitpunkt des Vertragsschlusses vereinbarten Preise zuzüglich gesetzlicher Umsatzsteuer, soweit diese anfällt.</p><p>Die Abrechnung erfolgt je nach gebuchtem Tarif monatlich oder jährlich im Voraus. Zahlungen können über die jeweils angebotenen Zahlungsmethoden, insbesondere über Stripe, abgewickelt werden.</p><p>Der Kunde ist dafür verantwortlich, dass hinterlegte Zahlungsdaten aktuell sind und Zahlungen fristgerecht erfolgen. Bei Zahlungsverzug kann CraftWise nach vorheriger Mahnung und angemessener Fristsetzung den Zugang zur Software sperren oder den Vertrag kündigen, soweit gesetzlich zulässig.</p></div>
        <div class="legal-section"><h2>7. Testphase</h2><p>CraftWise kann eine kostenlose Testphase anbieten. Umfang und Dauer der Testphase ergeben sich aus dem jeweiligen Angebot. Nach Ablauf der Testphase wird die Nutzung nur fortgesetzt, wenn der Kunde ein kostenpflichtiges Abonnement abschließt oder die Fortsetzung ausdrücklich vereinbart wurde.</p><p>CraftWise kann Testphasen beschränken, ablehnen oder beenden, wenn Anzeichen für Missbrauch, Mehrfachregistrierungen zur Umgehung von Zahlungsfristen oder eine Nutzung außerhalb des vorgesehenen Testzwecks bestehen.</p></div>
        <div class="legal-section"><h2>8. Pflichten des Kunden</h2><p>Der Kunde ist verpflichtet, die Software nur rechtmäßig und vertragsgemäß zu nutzen. Er darf insbesondere keine rechtswidrigen, diskriminierenden, verletzenden, sicherheitsgefährdenden oder gegen Rechte Dritter verstoßenden Inhalte einstellen.</p><p>Der Kunde ist für die von ihm und seinen Nutzern eingegebenen Daten, Dokumente, Kommunikationsinhalte, Rechnungen, Angebote und sonstigen Inhalte verantwortlich. Dazu gehört auch die Einhaltung steuerlicher, handelsrechtlicher, arbeitsrechtlicher und datenschutzrechtlicher Anforderungen, soweit diese den Kunden betreffen.</p><p>Der Kunde ist verpflichtet, angemessene eigene Sicherungs- und Prüfprozesse einzurichten, insbesondere für geschäftskritische Dokumente, Rechnungen, steuerrelevante Unterlagen und Datenexporte.</p></div>
        <div class="legal-section"><h2>9. Finanzdokumente, Rechnungen und rechtliche Verantwortung</h2><p>CraftWise kann Funktionen zur Erstellung und Verwaltung von Angeboten, Auftragsbestätigungen, Rechnungen, Gutschriften, Lieferscheinen oder sonstigen Geschäftsdokumenten bereitstellen.</p><p>CraftWise stellt technische Werkzeuge bereit, ersetzt jedoch keine steuerliche, rechtliche oder buchhalterische Beratung. Der Kunde bleibt verantwortlich für die inhaltliche Richtigkeit, Vollständigkeit, gesetzliche Pflichtangaben, steuerliche Behandlung, Aufbewahrung, Prüfung und rechtzeitige Übermittlung seiner Dokumente.</p><p>Soweit gesetzliche Anforderungen an elektronische Rechnungen, strukturierte Rechnungsformate oder Exporte bestehen, ist der Kunde dafür verantwortlich zu prüfen, ob die jeweilige CraftWise Funktion für seinen konkreten Anwendungsfall geeignet ist. Verbindliche Zusagen gelten nur, wenn sie ausdrücklich in der Leistungsbeschreibung oder vertraglich vereinbart sind.</p></div>
        <div class="legal-section"><h2>10. Datenschutz und Auftragsverarbeitung</h2><p>Soweit CraftWise personenbezogene Daten im Auftrag des Kunden verarbeitet, erfolgt dies auf Grundlage eines Auftragsverarbeitungsvertrags nach Art. 28 DSGVO.</p><p>Der Kunde bleibt Verantwortlicher für die Rechtmäßigkeit der Verarbeitung der von ihm in CraftWise eingegebenen personenbezogenen Daten. Weitere Informationen ergeben sich aus der Datenschutzerklärung und dem AVV.</p></div>
        <div class="legal-section"><h2>11. Optionale Integrationen und Drittanbieter</h2><p>CraftWise kann Schnittstellen oder Integrationen zu Drittanbietern anbieten, z. B. Kalender-, Meeting-, Zahlungs-, Buchhaltungs- oder Exportdienste. Der Kunde entscheidet, ob er solche Integrationen aktiviert und welche Daten übertragen werden.</p><p>Drittanbieterleistungen unterliegen regelmäßig den Bedingungen und Datenschutzinformationen des jeweiligen Drittanbieters. CraftWise haftet nicht für Verfügbarkeit, Funktionsweise oder Änderungen von Drittanbieterdiensten, soweit CraftWise diese nicht selbst kontrolliert.</p></div>
        <div class="legal-section"><h2>12. Kundendaten und Datenexport</h2><p>Die vom Kunden eingegebenen Inhalte und Daten verbleiben im Verhältnis der Parteien beim Kunden. CraftWise erhält daran nur die Rechte, die für Betrieb, Bereitstellung, Sicherung, Support und Weiterentwicklung der Software erforderlich sind.</p><p>Der Kunde sollte vor Vertragsende die von ihm benötigten Daten exportieren, soweit Exportfunktionen verfügbar sind. Nach Vertragsende kann CraftWise Daten nach Maßgabe des AVV und gesetzlicher Vorgaben löschen oder anonymisieren.</p></div>
        <div class="legal-section"><h2>13. Referral-Programm und Rabatte</h2><p>Sofern CraftWise ein Referral-Programm oder Rabatte anbietet, gelten die jeweils veröffentlichten oder individuell mitgeteilten Bedingungen. Rabatte sind nicht bar auszahlbar und nur auf laufende oder künftige Forderungen anrechenbar, soweit nichts anderes vereinbart ist.</p><p>CraftWise kann Referral-Programme oder freiwillige Rabattaktionen für die Zukunft ändern, aussetzen oder beenden. Bereits verbindlich gewährte Rabatte bleiben unberührt, soweit nichts anderes vereinbart wurde.</p><p>Die steuerliche Behandlung von Vorteilen, Rabatten oder Empfehlungsprämien beim Kunden liegt in dessen Verantwortung.</p></div>
        <div class="legal-section"><h2>14. Vertragslaufzeit und Kündigung</h2><p>Die Vertragslaufzeit richtet sich nach dem gebuchten Tarif oder der individuellen Vereinbarung. Bei monatlicher Abrechnung beträgt die Mindestlaufzeit regelmäßig einen Monat, bei jährlicher Abrechnung regelmäßig zwölf Monate.</p><p>Der Vertrag verlängert sich jeweils um den gewählten Abrechnungszeitraum, wenn er nicht vor Beginn der Verlängerung gekündigt wird, soweit nichts anderes vereinbart ist.</p><p>Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt. Ein wichtiger Grund liegt insbesondere vor, wenn eine Partei trotz Abmahnung wesentlich gegen vertragliche Pflichten verstößt.</p></div>
        <div class="legal-section"><h2>15. Sperrung des Zugangs</h2><p>CraftWise kann den Zugang des Kunden oder einzelner Nutzer vorübergehend sperren, wenn konkrete Anhaltspunkte für rechtswidrige Nutzung, Sicherheitsrisiken, erhebliche Vertragsverstöße, unbefugte Zugriffe oder Zahlungsverzug bestehen.</p><p>CraftWise berücksichtigt dabei die berechtigten Interessen des Kunden und beschränkt eine Sperrung soweit möglich auf den erforderlichen Umfang.</p></div>
        <div class="legal-section"><h2>16. Gewährleistung</h2><p>Es gelten die gesetzlichen Gewährleistungsrechte, soweit in diesen AGB nichts Abweichendes wirksam geregelt ist.</p><p>Bei Softwareleistungen schuldet CraftWise nicht, dass die Software jeden denkbaren Zweck des Kunden erfüllt oder mit jeder Drittsoftware, jedem Gerät oder jeder individuellen Systemumgebung des Kunden kompatibel ist, sofern dies nicht ausdrücklich vereinbart wurde.</p></div>
        <div class="legal-section"><h2>17. Haftung</h2><p>CraftWise haftet unbeschränkt bei Vorsatz und grober Fahrlässigkeit, bei Verletzung von Leben, Körper oder Gesundheit, nach dem Produkthaftungsgesetz sowie im Umfang ausdrücklich übernommener Garantien.</p><p>Bei leichter Fahrlässigkeit haftet CraftWise nur bei Verletzung wesentlicher Vertragspflichten. Wesentliche Vertragspflichten sind Pflichten, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags überhaupt erst ermöglicht und auf deren Einhaltung der Kunde regelmäßig vertrauen darf. In diesem Fall ist die Haftung auf den vertragstypischen, vorhersehbaren Schaden begrenzt.</p><p>Im Übrigen ist die Haftung ausgeschlossen, soweit gesetzlich zulässig. Die Haftungsregelungen gelten auch zugunsten der gesetzlichen Vertreter, Mitarbeiter und Erfüllungsgehilfen von CraftWise.</p></div>
        <div class="legal-section"><h2>18. Änderungen der AGB</h2><p>CraftWise kann diese AGB mit Wirkung für die Zukunft ändern, wenn ein sachlicher Grund besteht, insbesondere bei Änderungen der Rechtslage, technischen Entwicklungen, neuen Funktionen oder Anpassungen des Geschäftsmodells.</p><p>Über wesentliche Änderungen informiert CraftWise den Kunden in Textform oder innerhalb der Plattform. Widerspricht der Kunde nicht innerhalb einer angemessenen Frist, gelten die Änderungen als angenommen, wenn CraftWise auf diese Folge ausdrücklich hingewiesen hat. Bei wesentlichen Änderungen, die das Vertragsgleichgewicht erheblich zulasten des Kunden verschieben, bleibt eine ausdrückliche Zustimmung erforderlich.</p></div>
        <div class="legal-section"><h2>19. Schlussbestimmungen</h2><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Ausschließlicher Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit dem Vertrag ist, soweit gesetzlich zulässig, der Sitz der CraftWise GmbH.</p><p>Sollten einzelne Bestimmungen unwirksam sein oder werden, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt. Anstelle der unwirksamen Bestimmung gelten die gesetzlichen Vorschriften.</p></div>
      `,
  },
  {
    key: "TERMS_CONDITIONS",
    locale: "en",
    title: "Terms and Conditions",
    metaTitle: "Terms and Conditions | CraftWise",
    metaDescription: "The contractual terms governing the use of the CraftWise SaaS platform and related services.",
    heroTitle: "Terms and Conditions",
    heroSemiTitle: "Last updated: 17 June 2026",
    heroDescription: "The contractual terms governing the use of the CraftWise SaaS platform and related services.",
    heroImage: "/images/thumbs/terms.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Scope and contracting party</h2><p>These Terms and Conditions govern the contractual relationship between CraftWise GmbH, Ulmenweg 12, 64331 Weiterstadt, Germany (“CraftWise”), and its customers.</p><p>CraftWise provides services exclusively to business customers. Consumers are not entitled to enter into a contract.</p><p>Deviating, conflicting or supplementary terms and conditions of the customer do not become part of the contract unless CraftWise expressly agrees to their application in text form.</p></div>
        <div class="legal-section"><h2>2. Services of CraftWise</h2><p>CraftWise provides a software-as-a-service solution for craft, trade and project-oriented businesses. The software may include functions for project management, tasks, appointments, time tracking, document management, communication, quote and invoice management and mobile use.</p><p>The specific scope of functions depends on the plan booked, the service description on the website, the offer or a separate agreement. Customisations, integrations, training or consulting services are owed only if expressly agreed.</p><p>CraftWise may further develop, update and adapt the software to technical, legal or commercial requirements, provided that the contractually agreed core benefit is not materially impaired.</p></div>
        <div class="legal-section"><h2>3. Registration, account and authorised use</h2><p>The customer must provide complete and accurate information during registration and contract conclusion and keep such information up to date.</p><p>The customer is responsible for all activities carried out through its account or user accounts created by it. Access credentials must be kept confidential and protected against third-party access.</p><p>The customer ensures that only authorised persons use the software and that user roles and permissions are assigned appropriately.</p></div>
        <div class="legal-section"><h2>4. Rights of use</h2><p>CraftWise grants the customer a simple, non-exclusive, non-transferable and non-sublicensable right to use the software for its own business purposes for the duration of the contract and within the agreed scope.</p><p>Making the software available to third parties, resale, reverse engineering, circumvention of technical protection measures, abusive use or use outside the agreed scope is prohibited unless mandatorily permitted by law.</p></div>
        <div class="legal-section"><h2>5. Availability, maintenance and support</h2><p>CraftWise endeavours to ensure high availability of the software. However, specific availability or uninterrupted usability is owed only if expressly agreed.</p><p>Temporary restrictions may arise in particular due to maintenance, updates, security measures, third-party provider disruptions, force majeure, internet disruptions or events outside CraftWise’s control.</p><p>Support is provided during normal business hours through the support channels offered by CraftWise, in particular by email or within the platform. Response times are binding only if expressly agreed.</p></div>
        <div class="legal-section"><h2>6. Prices, billing and payment</h2><p>The prices agreed at the time of contract conclusion apply plus statutory VAT where applicable.</p><p>Billing is monthly or annually in advance depending on the selected plan. Payments may be processed using the payment methods offered, in particular through Stripe.</p><p>The customer is responsible for keeping payment details up to date and ensuring timely payment. In the event of payment default, CraftWise may, after prior reminder and reasonable grace period, suspend access to the software or terminate the contract to the extent permitted by law.</p></div>
        <div class="legal-section"><h2>7. Trial period</h2><p>CraftWise may offer a free trial period. Scope and duration of the trial period are determined by the respective offer. After expiry of the trial period, use continues only if the customer enters into a paid subscription or continuation is expressly agreed.</p><p>CraftWise may restrict, refuse or end trial periods if there are indications of abuse, multiple registrations to circumvent payment periods or use outside the intended trial purpose.</p></div>
        <div class="legal-section"><h2>8. Customer obligations</h2><p>The customer must use the software only lawfully and in accordance with the contract. In particular, the customer must not upload unlawful, discriminatory, infringing, security-endangering or third-party-rights-infringing content.</p><p>The customer is responsible for all data, documents, communications, invoices, quotes and other content entered by it and its users. This includes compliance with tax, commercial, labour and data protection requirements insofar as they concern the customer.</p><p>The customer must maintain appropriate own backup and review processes, in particular for business-critical documents, invoices, tax-relevant records and data exports.</p></div>
        <div class="legal-section"><h2>9. Financial documents, invoices and legal responsibility</h2><p>CraftWise may provide functions for creating and managing quotes, order confirmations, invoices, credit notes, delivery notes or other business documents.</p><p>CraftWise provides technical tools but does not replace tax, legal or accounting advice. The customer remains responsible for content accuracy, completeness, statutory mandatory information, tax treatment, retention, review and timely transmission of its documents.</p><p>Where legal requirements for electronic invoices, structured invoice formats or exports apply, the customer is responsible for checking whether the relevant CraftWise function is suitable for its specific use case. Binding commitments apply only if expressly stated in the service description or contractually agreed.</p></div>
        <div class="legal-section"><h2>10. Data protection and processing on behalf</h2><p>Where CraftWise processes personal data on behalf of the customer, this is done on the basis of a Data Processing Agreement pursuant to Art. 28 GDPR.</p><p>The customer remains controller for the lawfulness of processing of personal data entered by it into CraftWise. Further information is provided in the Privacy Policy and DPA.</p></div>
        <div class="legal-section"><h2>11. Optional integrations and third-party providers</h2><p>CraftWise may offer interfaces or integrations with third-party providers, e.g. calendar, meeting, payment, accounting or export services. The customer decides whether to activate such integrations and which data is transmitted.</p><p>Third-party services are generally subject to the terms and privacy information of the respective third-party provider. CraftWise is not liable for availability, functionality or changes to third-party services insofar as CraftWise does not control them.</p></div>
        <div class="legal-section"><h2>12. Customer data and data export</h2><p>As between the parties, content and data entered by the customer remain with the customer. CraftWise receives only the rights required to operate, provide, secure, support and improve the software.</p><p>The customer should export required data before contract termination where export functions are available. After contract termination, CraftWise may delete or anonymise data in accordance with the DPA and legal requirements.</p></div>
        <div class="legal-section"><h2>13. Referral programme and discounts</h2><p>Where CraftWise offers a referral programme or discounts, the terms published or individually communicated apply. Discounts are not payable in cash and may be applied only to ongoing or future claims unless otherwise agreed.</p><p>CraftWise may change, suspend or end referral programmes or voluntary discount campaigns for the future. Discounts already granted on a binding basis remain unaffected unless otherwise agreed.</p><p>The customer is responsible for the tax treatment of benefits, discounts or referral rewards.</p></div>
        <div class="legal-section"><h2>14. Contract term and termination</h2><p>The contract term depends on the selected plan or individual agreement. For monthly billing, the minimum term is generally one month; for annual billing, generally twelve months.</p><p>The contract renews for the selected billing period unless terminated before the renewal begins, unless otherwise agreed.</p><p>The right to terminate for cause remains unaffected. Cause exists in particular if a party materially breaches contractual obligations despite warning.</p></div>
        <div class="legal-section"><h2>15. Suspension of access</h2><p>CraftWise may temporarily suspend access of the customer or individual users if there are specific indications of unlawful use, security risks, material contractual breaches, unauthorised access or payment default.</p><p>CraftWise will take the customer’s legitimate interests into account and limit suspension to the required extent where possible.</p></div>
        <div class="legal-section"><h2>16. Warranty</h2><p>Statutory warranty rights apply unless effectively modified in these Terms.</p><p>For software services, CraftWise does not owe that the software fulfils every conceivable purpose of the customer or is compatible with every third-party software, device or individual system environment of the customer unless expressly agreed.</p></div>
        <div class="legal-section"><h2>17. Liability</h2><p>CraftWise is liable without limitation for intent and gross negligence, injury to life, body or health, under the German Product Liability Act and to the extent of expressly assumed guarantees.</p><p>In cases of slight negligence, CraftWise is liable only for breach of material contractual obligations. Material contractual obligations are obligations whose fulfilment enables proper performance of the contract and on whose compliance the customer may regularly rely. In such cases, liability is limited to the typical, foreseeable damage.</p><p>Otherwise, liability is excluded to the extent permitted by law. The liability provisions also apply for the benefit of CraftWise’s legal representatives, employees and vicarious agents.</p></div>
        <div class="legal-section"><h2>18. Changes to the Terms</h2><p>CraftWise may amend these Terms with effect for the future where there is an objective reason, in particular changes in law, technical developments, new functions or adjustments to the business model.</p><p>CraftWise will inform the customer of material changes in text form or within the platform. If the customer does not object within a reasonable period, the changes are deemed accepted if CraftWise has expressly pointed out this consequence. Material changes that significantly shift the contractual balance to the customer’s disadvantage require express consent.</p></div>
        <div class="legal-section"><h2>19. Final provisions</h2><p>German law applies, excluding the UN Convention on Contracts for the International Sale of Goods. Exclusive place of jurisdiction for all disputes arising from or in connection with the contract is, to the extent legally permitted, the registered office of CraftWise GmbH.</p><p>If any provision is or becomes invalid, the validity of the remaining provisions remains unaffected. The statutory provisions apply in place of the invalid provision.</p></div>
      `,
  },
  {
    key: "LEGAL_NOTICE",
    locale: "de",
    title: "Impressum",
    metaTitle: "Impressum | CraftWise",
    metaDescription: "CraftWise GmbHUlmenweg 1264331 WeiterstadtDeutschlandVertreten durchFelix Pritzsche, Geschäftsführer",
    heroTitle: "Impressum",
    heroSemiTitle: "Angaben gemäß § 5 DDG und § 18 Abs. 2 MStV",
    heroDescription: "<strong>Anbieter</strong><br/>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Deutschland<br/><br/><strong>Vertreten durch</strong><br/>Felix Pritzsche, Geschäftsführer",
    heroImage: "/images/thumbs/legal-notice.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-grid legal-grid--2">
        <div class="legal-card"><h3>Kontakt</h3><p><strong>Telefon:</strong> +49 69 58003098</p><p><strong>E-Mail:</strong> support@craft-wise.de</p></div>
        <div class="legal-card"><h3>Handelsregister</h3><p>Eingetragen im Handelsregister.</p><p>Registergericht: Amtsgericht Darmstadt</p><p>Handelsregisternummer: HRB 108362</p></div>
        <div class="legal-card"><h3>Umsatzsteuer-ID</h3><p>Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: DE458627363</p></div>
        <div class="legal-card"><h3>Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV</h3><p>Felix Pritzsche</p><p>CraftWise GmbH</p><p>Ulmenweg 12</p><p>64331 Weiterstadt</p><p>Deutschland</p></div>
      </div>
        <div class="legal-section"><h2>Online-Streitbeilegung und Verbraucherstreitbeilegung</h2><p>Die CraftWise GmbH richtet sich mit ihren Leistungen ausschließlich an Unternehmer im Sinne von § 14 BGB. Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p></div>
        <div class="legal-section"><h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Wir sind jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.</p><p>Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben unberührt. Eine Haftung ist insoweit jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen entfernen wir diese Inhalte unverzüglich.</p></div>
        <div class="legal-section"><h2>Haftung für Links</h2><p>Unsere Website kann Links zu externen Websites Dritter enthalten. Auf deren Inhalte haben wir keinen Einfluss. Deshalb können wir für diese fremden Inhalte keine Gewähr übernehmen. Für die Inhalte verlinkter Seiten ist stets der jeweilige Anbieter oder Betreiber verantwortlich. Bei Bekanntwerden von Rechtsverletzungen entfernen wir entsprechende Links unverzüglich.</p></div>
        <div class="legal-section"><h2>Urheberrecht</h2><p>Die durch uns erstellten Inhalte und Werke auf dieser Website unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung oder sonstige Nutzung außerhalb der Grenzen des Urheberrechts bedürfen unserer vorherigen Zustimmung, sofern sie nicht gesetzlich erlaubt sind.</p></div>
      `,
  },
  {
    key: "LEGAL_NOTICE",
    locale: "en",
    title: "Legal Notice",
    metaTitle: "Legal Notice | CraftWise",
    metaDescription: "CraftWise GmbHUlmenweg 1264331 WeiterstadtGermanyRepresented byFelix Pritzsche, Managing Director",
    heroTitle: "Legal Notice",
    heroSemiTitle: "Information pursuant to Section 5 German Digital Services Act (DDG) and Section 18(2) German Interstate Media Treaty (MStV)",
    heroDescription: "<strong>Provider</strong><br/>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Germany<br/><br/><strong>Represented by</strong><br/>Felix Pritzsche, Managing Director",
    heroImage: "/images/thumbs/legal-notice.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-grid legal-grid--2">
        <div class="legal-card"><h3>Contact</h3><p><strong>Phone:</strong> +49 69 58003098</p><p><strong>Email:</strong> support@craft-wise.de</p></div>
        <div class="legal-card"><h3>Commercial register</h3><p>Registered with the commercial register.</p><p>Register court: Local Court of Darmstadt</p><p>Commercial register number: HRB 108362</p></div>
        <div class="legal-card"><h3>VAT ID</h3><p>VAT identification number pursuant to Section 27a German VAT Act: DE458627363</p></div>
        <div class="legal-card"><h3>Responsible for content pursuant to Section 18(2) MStV</h3><p>Felix Pritzsche</p><p>CraftWise GmbH</p><p>Ulmenweg 12</p><p>64331 Weiterstadt</p><p>Germany</p></div>
      </div>
        <div class="legal-section"><h2>Online dispute resolution and consumer dispute resolution</h2><p>CraftWise GmbH provides its services exclusively to business customers within the meaning of Section 14 German Civil Code (BGB). We are not obliged or willing to participate in dispute resolution proceedings before a consumer arbitration board.</p></div>
        <div class="legal-section"><h2>Liability for content</h2><p>As a service provider, we are responsible for our own content on these pages in accordance with general law. However, we are not obliged to monitor transmitted or stored third-party information or to investigate circumstances indicating unlawful activity.</p><p>Obligations to remove or block the use of information under general law remain unaffected. Liability in this respect is only possible from the time we become aware of a specific legal violation. If we become aware of such violations, we will remove the relevant content without undue delay.</p></div>
        <div class="legal-section"><h2>Liability for links</h2><p>Our website may contain links to external third-party websites. We have no influence over their content and therefore cannot assume any liability for such external content. The respective provider or operator of the linked pages is always responsible for their content. If we become aware of legal violations, we will remove such links without undue delay.</p></div>
        <div class="legal-section"><h2>Copyright</h2><p>The content and works created by us on this website are subject to German copyright law. Reproduction, editing, distribution or any other use outside the limits of copyright law requires our prior consent unless permitted by law.</p></div>
      `,
  },
  {
    key: "DATA_PROCESSING",
    locale: "de",
    title: "Auftragsverarbeitungsvertrag (AVV)",
    metaTitle: "Auftragsverarbeitungsvertrag (AVV) | CraftWise",
    metaDescription: "Verarbeitung personenbezogener Daten durch die CraftWise GmbH als Auftragsverarbeiter im Auftrag des Kunden als Verantwortlicher im Sinne der DSGVO.",
    heroTitle: "Auftragsverarbeitung (AVV)",
    heroSemiTitle: "Stand: 17. Juni 2026",
    heroDescription: "Dieser Auftragsverarbeitungsvertrag (“AVV”) regelt die Verarbeitung personenbezogener Daten durch die CraftWise GmbH als Auftragsverarbeiter im Auftrag des jeweiligen Kunden als Verantwortlicher im Sinne der Datenschutz-Grundverordnung (“DSGVO”). Der AVV ist Bestandteil des Hauptvertrags über die Nutzung der CraftWise Software-as-a-Service-Plattform.",
    heroImage: "/images/data-processing/hero.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Vertragsparteien</h2><p>Verantwortlicher ist der jeweilige Kunde, der die CraftWise Plattform als Unternehmen nutzt.</p><p><strong>Auftragsverarbeiter ist:</strong></p><p>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Deutschland<br/>E-Mail: support@craft-wise.de</p></div>
        <div class="legal-section"><h2>2. Gegenstand, Dauer und Weisungen</h2><p>Gegenstand der Verarbeitung ist die Bereitstellung, der Betrieb, die Wartung, der Support und die Absicherung der CraftWise Plattform, einschließlich Web- und Mobile-App, Projektmanagement, Terminplanung, Zeiterfassung, Dokumentenverwaltung, Kommunikation, Angebots- und Rechnungswesen sowie optional aktivierter Integrationen.</p><p>Die Verarbeitung beginnt mit Wirksamwerden des Hauptvertrags und endet mit dessen Beendigung, vorbehaltlich gesetzlicher Aufbewahrungspflichten und der in diesem AVV geregelten Löschfristen.</p><p>CraftWise verarbeitet personenbezogene Daten ausschließlich auf dokumentierte Weisung des Verantwortlichen, sofern CraftWise nicht durch Unionsrecht oder deutsches Recht zu einer Verarbeitung verpflichtet ist. Die Konfiguration, Administration und Nutzung der Plattform durch den Verantwortlichen und seine berechtigten Nutzer gilt als dokumentierte Weisung. Weitere Weisungen können in Textform, z. B. per E-Mail oder Support-Ticket, erteilt werden.</p></div>
        <div class="legal-section"><h2>3. Pflichten des Verantwortlichen</h2><p>Der Verantwortliche ist für die Rechtmäßigkeit der Verarbeitung, die Auswahl der in der Plattform verarbeiteten Daten, die Information betroffener Personen, die Wahrung der Betroffenenrechte und die Einhaltung der Grundsätze der DSGVO verantwortlich.</p><p>Der Verantwortliche stellt sicher, dass nur erforderliche personenbezogene Daten in CraftWise verarbeitet werden. Besondere Kategorien personenbezogener Daten nach Art. 9 DSGVO, insbesondere Gesundheitsdaten, dürfen nur verarbeitet werden, wenn hierfür eine geeignete Rechtsgrundlage besteht. Angaben zu Krankheitstagen sollten ohne Diagnosen oder medizinische Details erfolgen.</p><p>Der Verantwortliche steuert die Nutzer, Rollen und Berechtigungen innerhalb seines Accounts und informiert CraftWise unverzüglich über unzulässige Weisungen, Sicherheitsvorfälle oder Unregelmäßigkeiten, die er im Zusammenhang mit der Verarbeitung feststellt.</p></div>
        <div class="legal-section"><h2>4. Pflichten von CraftWise</h2><p><strong>CraftWise verpflichtet sich insbesondere:</strong></p><ul><li>personenbezogene Daten nur auf dokumentierte Weisung des Verantwortlichen zu verarbeiten</li><li>die zur Verarbeitung befugten Personen zur Vertraulichkeit zu verpflichten</li><li>geeignete technische und organisatorische Maßnahmen nach Art. 32 DSGVO umzusetzen</li><li>Unterauftragsverarbeiter nur nach Maßgabe dieses AVV einzusetzen</li><li>den Verantwortlichen nach Möglichkeit bei Betroffenenrechten, Datenschutz-Folgenabschätzungen und Konsultationen zu unterstützen</li><li>Datenschutzverletzungen nach Maßgabe dieses AVV zu melden</li><li>personenbezogene Daten nach Vertragsende zurückzugeben, zu löschen oder zu anonymisieren, soweit keine gesetzlichen Aufbewahrungspflichten entgegenstehen</li><li>dem Verantwortlichen geeignete Nachweise zur Einhaltung dieses AVV bereitzustellen.</li></ul></div>
        <div class="legal-section"><h2>5. Vertraulichkeit, Zugriffsschutz und Mandantentrennung</h2><p>CraftWise stellt sicher, dass Personen, die Zugriff auf personenbezogene Daten erhalten können, zur Vertraulichkeit verpflichtet sind.</p><p>Administrative Zugriffe werden auf einen berechtigten Personenkreis beschränkt und nach dem Need-to-know-Prinzip vergeben. CraftWise setzt ein Rollen- und Berechtigungskonzept ein und schützt Zugriffe durch angemessene technische Maßnahmen, insbesondere Authentifizierung, Zugriffsbeschränkungen und, soweit technisch verfügbar, Protokollierung sicherheitsrelevanter Ereignisse.</p><p>Kundendaten werden logisch getrennt verarbeitet. Der Verantwortliche bleibt für die sachgerechte Vergabe und Pflege der Nutzerrollen innerhalb seines Kundenkontos verantwortlich.</p></div>
        <div class="legal-section"><h2>6. Technische und organisatorische Maßnahmen</h2><p>CraftWise setzt geeignete technische und organisatorische Maßnahmen unter Berücksichtigung des Stands der Technik, der Implementierungskosten, der Art, des Umfangs, der Umstände und Zwecke der Verarbeitung sowie der Risiken für betroffene Personen ein. Die wesentlichen Maßnahmen sind in Anlage 2 beschrieben.</p><p>CraftWise darf Maßnahmen ändern oder weiterentwickeln, sofern das Sicherheitsniveau insgesamt nicht wesentlich unterschritten wird.</p></div>
        <div class="legal-section"><h2>7. Unterauftragsverarbeiter</h2><p>Der Verantwortliche erteilt CraftWise eine allgemeine Genehmigung zum Einsatz von Unterauftragsverarbeitern. Die bei Vertragsschluss wesentlichen Unterauftragsverarbeiter sind in Anlage 3 aufgeführt.</p><p>CraftWise informiert den Verantwortlichen mindestens 14 Tage vor Hinzunahme oder Austausch wesentlicher Unterauftragsverarbeiter in Textform oder über eine geeignete elektronische Mitteilung. Der Verantwortliche kann aus wichtigem datenschutzrechtlichem Grund innerhalb dieser Frist widersprechen.</p><p>Im Falle eines berechtigten Widerspruchs bemüht sich CraftWise um eine zumutbare Alternative. Ist eine Alternative nicht möglich, kann der Verantwortliche den betroffenen Teil der Leistung außerordentlich kündigen. CraftWise stellt sicher, dass Unterauftragsverarbeiter vertraglich zu Datenschutzpflichten verpflichtet werden, die den Anforderungen von Art. 28 DSGVO entsprechen.</p></div>
        <div class="legal-section"><h2>8. Drittlandübermittlungen</h2><p>Die CraftWise App ist grundsätzlich auf Verarbeitung in EU-Regionen ausgelegt, soweit dies für die jeweilige Infrastrukturleistung verfügbar und konfiguriert ist. Gleichwohl können Drittlandzugriffe oder Drittlandübermittlungen nicht in allen Fällen ausgeschlossen werden, insbesondere bei globalen Infrastrukturleistungen, Support, Push-Benachrichtigungen, Zahlungsabwicklung oder optionalen Integrationen.</p><p>Sofern eine Drittlandübermittlung erforderlich ist, stellt CraftWise geeignete Garantien nach Art. 44 ff. DSGVO sicher, insbesondere Angemessenheitsbeschlüsse der EU-Kommission, EU-Standardvertragsklauseln und ergänzende technische oder organisatorische Maßnahmen, soweit erforderlich.</p></div>
        <div class="legal-section"><h2>9. Datenschutzverletzungen</h2><p>CraftWise informiert den Verantwortlichen unverzüglich, spätestens innerhalb von 48 Stunden nach Kenntnis, über eine Datenschutzverletzung, die personenbezogene Daten des Verantwortlichen betrifft.</p><p>Die Mitteilung enthält, soweit verfügbar, Art der Verletzung, Kategorien und ungefähre Anzahl betroffener Personen und Datensätze, wahrscheinliche Folgen, ergriffene oder vorgeschlagene Maßnahmen und einen Ansprechpartner. CraftWise dokumentiert Datenschutzverletzungen intern und unterstützt den Verantwortlichen nach Möglichkeit bei seinen gesetzlichen Pflichten.</p></div>
        <div class="legal-section"><h2>10. Unterstützungspflichten</h2><p>CraftWise unterstützt den Verantwortlichen nach Möglichkeit bei der Erfüllung von Betroffenenrechten nach Art. 12 bis 22 DSGVO, bei Datenschutz-Folgenabschätzungen nach Art. 35 DSGVO und bei Konsultationen nach Art. 36 DSGVO, soweit die angefragten Informationen CraftWise zur Verfügung stehen und die Verarbeitung durch CraftWise betreffen.</p><p>Anfragen betroffener Personen, die CraftWise direkt erreichen, leitet CraftWise an den Verantwortlichen weiter, sofern eine Zuordnung möglich ist. Die rechtliche Prüfung und Beantwortung bleibt Aufgabe des Verantwortlichen.</p><p>Unterstützungsleistungen, die über die vertraglich geschuldete Plattformfunktionalität hinausgehen, können nach Aufwand abgerechnet werden, soweit dies im Hauptvertrag oder in einer gesonderten Vereinbarung vorgesehen ist.</p></div>
        <div class="legal-section"><h2>11. Kontrollrechte und Nachweise</h2><p>Der Verantwortliche kann die Einhaltung dieses AVV überprüfen. CraftWise stellt hierzu auf Anfrage geeignete Informationen und Nachweise bereit.</p><p>Audits erfolgen nach vorheriger Ankündigung mit angemessener Frist, während üblicher Geschäftszeiten und unter Beachtung von Geschäftsgeheimnissen, Sicherheitsanforderungen und Rechten anderer Kunden. CraftWise kann statt eines Vor-Ort-Audits gleichwertige Nachweise, Dokumentenprüfungen, Remote-Audits oder Zertifizierungen anbieten, soweit dies angemessen ist.</p><p>Der Verantwortliche trägt die angemessenen Kosten eines Vor-Ort-Audits, sofern das Audit keinen wesentlichen Datenschutzverstoß von CraftWise aufdeckt.</p></div>
        <div class="legal-section"><h2>12. Rückgabe, Löschung und Vertragsende</h2><p>Der Verantwortliche kann seine Daten vor Vertragsende exportieren, soweit entsprechende Funktionen bereitgestellt werden.</p><p>Nach Beendigung des Hauptvertrags löscht oder anonymisiert CraftWise personenbezogene Daten des Verantwortlichen innerhalb von 30 Tagen, soweit keine gesetzlichen Aufbewahrungspflichten, berechtigten Interessen oder technischen Übergangsfristen entgegenstehen.</p><p>Daten in Backups werden im Rahmen regulärer Backup-Zyklen überschrieben. Eine sofortige Löschung aus Backups ist technisch nicht in allen Fällen möglich. Backup-Daten werden bis zur Löschung nicht für produktive Zwecke verwendet und angemessen geschützt.</p><p>Der Verantwortliche kann eine Löschbestätigung in Textform anfordern.</p></div>
        <div class="legal-section"><h2>13. Haftung</h2><p>Die Haftung richtet sich nach dem Hauptvertrag und den gesetzlichen Vorschriften, insbesondere Art. 82 DSGVO. Soweit CraftWise aufgrund einer Weisung des Verantwortlichen oder einer vom Verantwortlichen zu vertretenden rechtswidrigen Verarbeitung in Anspruch genommen wird, stellt der Verantwortliche CraftWise im Innenverhältnis von Ansprüchen frei, soweit dies gesetzlich zulässig ist.</p></div>
        <div class="legal-section"><h2>14. Schlussbestimmungen</h2><p>Änderungen und Ergänzungen dieses AVV bedürfen der Textform. Im Falle von Widersprüchen zwischen diesem AVV und dem Hauptvertrag gehen die Regelungen dieses AVV hinsichtlich datenschutzrechtlicher Pflichten vor.</p><p>Sollten einzelne Bestimmungen unwirksam sein, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt. Es gilt deutsches Recht.</p></div>
        <div class="legal-section"><h2>Anlage 1 - Beschreibung der Verarbeitung</h2><p>Gegenstand: Bereitstellung und Betrieb der CraftWise SaaS-Plattform für Projektmanagement, Zeiterfassung, Dokumente, Kommunikation, Angebots- und Rechnungswesen sowie optionale Integrationen.</p><p>Dauer: Dauer des Hauptvertrags; Löschung oder Anonymisierung nach Vertragsende nach Maßgabe dieses AVV.</p><p>Art der Verarbeitung: Erheben, Erfassen, Organisieren, Ordnen, Speichern, Anpassen, Auslesen, Abfragen, Verwenden, Offenlegen durch Übermittlung innerhalb der Plattform, Einschränken, Löschen und Anonymisieren.</p><p>Zwecke: Vertragserfüllung, Plattformbetrieb, Support, Sicherheit, Fehleranalyse, Wartung und Weiterentwicklung.</p><p>Betroffene Personen: Mitarbeiter und Nutzer des Verantwortlichen, Kunden und Ansprechpartner des Verantwortlichen, Projektbeteiligte, Subunternehmer, Lieferanten und sonstige Personen, deren Daten der Verantwortliche in CraftWise verarbeitet.</p><p>Datenkategorien: Stammdaten, Kontaktdaten, Nutzer- und Berechtigungsdaten, Projekt- und Auftragsdaten, Termin- und Kalenderdaten, Arbeitszeit- und Abwesenheitsdaten, Dokumente, Kommunikationsinhalte, Angebots- und Rechnungsdaten, Nutzungs- und Sicherheitsdaten.</p><p>Besondere Kategorien personenbezogener Daten: Nicht beabsichtigt. Freitextangaben oder Abwesenheitsangaben können im Einzelfall besondere Kategorien enthalten, wenn der Verantwortliche solche Daten eingibt. Der Verantwortliche steuert Inhalt, Rechtsgrundlage und Datenminimierung.</p><p>Speicherorte: App und Kernplattform: insbesondere Firebase / Google Cloud in EU-Regionen, soweit verfügbar und konfiguriert. Öffentliche Website: Hostinger. Einzelne technische Dienste, Push-Benachrichtigungen, Zahlungsabwicklung oder optionale Integrationen können zu Verarbeitungen außerhalb der EU bzw. des EWR führen, jeweils nach Maßgabe geeigneter Garantien.</p></div>
        <div class="legal-section"><h2>Anlage 2 - Technische und organisatorische Maßnahmen</h2><p><strong>Zugang, Zugriff und Authentifizierung:</strong></p><ul><li>Rollen- und Berechtigungskonzept nach Least-Privilege-Prinzip.</li><li>Administrative Zugänge nur für berechtigte Personen.</li><li>Starke Authentifizierung für administrative Zugänge, soweit verfügbar.</li><li>Protokollierung sicherheitsrelevanter Ereignisse, soweit technisch verfügbar.</li><li>Schutz vor missbräuchlichen Zugriffen, z. B. durch technische Begrenzungen und Monitoring.</li></ul><p><strong>Übertragungs- und Speicherverschlüsselung:</strong></p><ul><li>TLS-Verschlüsselung für Datenübertragung zwischen Client und Server.</li><li>Verschlüsselung im Ruhezustand durch eingesetzte Infrastrukturprovider nach deren Standard-Sicherheitsmechanismen.</li><li>Beschränkter Zugriff auf Systeme und Schlüssel nach Anbieter- und Berechtigungskonzept.</li></ul><p><strong>Verfügbarkeit, Backup und Wiederherstellung:</strong></p><ul><li>Nutzung von Backup-, Redundanz- und Wiederherstellungsfunktionen der eingesetzten Infrastrukturprovider.</li><li>Monitoring von Verfügbarkeit, Fehlern und sicherheitsrelevanten Ereignissen nach angemessenem Standard.</li><li>Incident-Response-Prozess für relevante Sicherheitsvorfälle.</li></ul><p><strong>Mandantentrennung:</strong></p><ul><li>Logische Trennung von Kundendaten innerhalb der Anwendung und Datenhaltung.</li><li>Trennung von Produktions- und Test-/Entwicklungsumgebungen, soweit technisch und organisatorisch angemessen.</li><li>Produktive Daten in Testsystemen nur, wenn erforderlich und mit geeigneten Schutzmaßnahmen.</li></ul><p><strong>Eingabe- und Weitergabekontrolle:</strong></p><ul><li>Zeitstempel und Nutzerzuordnung für relevante Aktionen, soweit technisch umgesetzt.</li><li>Beschränkung von Datenweitergaben auf das erforderliche Maß.</li><li>Gesicherte Schnittstellen zu Unterauftragsverarbeitern und Integrationspartnern.</li></ul><p><strong>Organisatorische Maßnahmen:</strong></p><ul><li>Vertraulichkeitsverpflichtung berechtigter Personen.</li><li>Interne Regeln für Zugriffe, Berechtigungen, Incident Handling und Change Management.</li><li>Sensibilisierung zu Datenschutz und Informationssicherheit.</li><li>Update- und Schwachstellenmanagement nach angemessenem Turnus.</li></ul></div>
        <div class="legal-section"><h2>Anlage 3 - Wesentliche Unterauftragsverarbeiter und Empfänger</h2><p>Die folgende Liste enthält die wesentlichen Anbieter, die für Betrieb, Bereitstellung oder Abrechnung der Plattform relevant sein können. Je nach aktivierten Funktionen können zusätzliche Anbieter hinzukommen.</p><p>Google Ireland Limited / Firebase / Google Cloud: App-Hosting, Authentifizierung, Datenbank, Storage, technische Plattformdienste; Region grundsätzlich EU, soweit verfügbar und konfiguriert; Drittlandtransfer mit geeigneten Garantien, sofern erforderlich.</p><p>Hostinger International Ltd.: Hosting der öffentlichen Website und damit verbundene technische Website-Daten; EU/EWR bzw. durch Hostinger eingesetzte Infrastruktur; Drittlandtransfer mit geeigneten Garantien, sofern erforderlich.</p><p>Stripe Payments Europe, Limited: Zahlungsabwicklung, Abrechnungsereignisse, Betrugsprävention und Compliance; EU/Irland und ggf. weitere Länder nach Stripe-Struktur; geeignete Garantien, sofern erforderlich.</p><p>Apple Inc. / Apple Distribution International Ltd.: Push-Benachrichtigungen für iOS-Geräte über Apple Push Notification service; global; geeignete Garantien, sofern erforderlich.</p><p>Google Ireland Limited / Google LLC: Push-Benachrichtigungen für Android-Geräte über Firebase Cloud Messaging; global; geeignete Garantien, sofern erforderlich.</p><p>Optional aktivierte Integrationen: Microsoft, Google, Zoom, DATEV, sevdesk, lexoffice oder vergleichbare Anbieter, soweit der Kunde diese Funktionen aktiviert; Zweck und Datenumfang richten sich nach der jeweiligen Integration.</p></div>
      `,
  },
  {
    key: "DATA_PROCESSING",
    locale: "en",
    title: "Data Processing Agreement (DPA)",
    metaTitle: "Data Processing Agreement (DPA) | CraftWise",
    metaDescription: "Processing of personal data by CraftWise GmbH as processor on behalf of the customer as controller within the meaning of the GDPR.",
    heroTitle: "Data Processing Agreement (DPA)",
    heroSemiTitle: "Last updated: 17 June 2026",
    heroDescription: "This Data Processing Agreement (“DPA”) governs the processing of personal data by CraftWise GmbH as processor on behalf of the respective customer as controller within the meaning of the General Data Protection Regulation (“GDPR”). The DPA forms part of the main agreement for the use of the CraftWise software-as-a-service platform.",
    heroImage: "/images/data-processing/hero.svg",
    publishedAt: "2026-06-17",
    bodyHtml: `
        <div class="legal-section"><h2>1. Parties</h2><p>The controller is the respective customer using the CraftWise platform as a business.</p><p><strong>The processor is:</strong></p><p>CraftWise GmbH<br/>Ulmenweg 12<br/>64331 Weiterstadt<br/>Germany<br/>Email: support@craft-wise.de</p></div>
        <div class="legal-section"><h2>2. Subject matter, term and instructions</h2><p>The subject matter of processing is the provision, operation, maintenance, support and security of the CraftWise platform, including web and mobile app, project management, scheduling, time tracking, document management, communication, quote and invoice management and optional integrations.</p><p>Processing begins when the main agreement becomes effective and ends upon termination of the main agreement, subject to statutory retention obligations and the deletion periods set out in this DPA.</p><p>CraftWise processes personal data only on documented instructions of the controller unless CraftWise is required to process such data by Union or German law. The configuration, administration and use of the platform by the controller and its authorised users constitutes documented instruction. Further instructions may be issued in text form, e.g. by email or support ticket.</p></div>
        <div class="legal-section"><h2>3. Duties of the controller</h2><p>The controller is responsible for the lawfulness of processing, the selection of data processed in the platform, information of data subjects, safeguarding data subject rights and compliance with the GDPR principles.</p><p>The controller ensures that only necessary personal data is processed in CraftWise. Special categories of personal data under Art. 9 GDPR, in particular health data, may be processed only if an appropriate legal basis exists. Sickness absence should be recorded without diagnoses or medical details.</p><p>The controller manages users, roles and permissions within its account and informs CraftWise without undue delay of unlawful instructions, security incidents or irregularities relating to processing.</p></div>
        <div class="legal-section"><h2>4. Duties of CraftWise</h2><p><strong>CraftWise undertakes in particular to:</strong></p><ul><li>process personal data only on documented instructions of the controller</li><li>ensure confidentiality of persons authorised to process personal data</li><li>implement appropriate technical and organisational measures pursuant to Art. 32 GDPR</li><li>engage subprocessors only in accordance with this DPA</li><li>assist the controller, where possible, with data subject rights, data protection impact assessments and consultations</li><li>notify personal data breaches in accordance with this DPA</li><li>return, delete or anonymise personal data after termination, unless statutory retention obligations apply</li><li>provide appropriate evidence of compliance with this DPA.</li></ul></div>
        <div class="legal-section"><h2>5. Confidentiality, access protection and tenant separation</h2><p>CraftWise ensures that persons who may access personal data are bound by confidentiality.</p><p>Administrative access is limited to authorised persons and granted on a need-to-know basis. CraftWise uses a roles and permissions concept and protects access through appropriate technical measures, in particular authentication, access restrictions and, where technically available, logging of security-relevant events.</p><p>Customer data is processed logically separated. The controller remains responsible for proper assignment and maintenance of user roles within its customer account.</p></div>
        <div class="legal-section"><h2>6. Technical and organisational measures</h2><p>CraftWise implements appropriate technical and organisational measures taking into account the state of the art, implementation costs, nature, scope, context and purposes of processing and the risks to data subjects. The essential measures are described in Annex 2.</p><p>CraftWise may change or improve measures provided that the overall level of security is not materially reduced.</p></div>
        <div class="legal-section"><h2>7. Subprocessors</h2><p>The controller grants CraftWise general authorisation to engage subprocessors. The material subprocessors at the time of contract conclusion are listed in Annex 3.</p><p>CraftWise will inform the controller at least 14 days before adding or replacing material subprocessors in text form or by suitable electronic notice. The controller may object within this period for important data protection reasons.</p><p>In the event of a justified objection, CraftWise will seek a reasonable alternative. If no alternative is possible, the controller may terminate the affected part of the service for cause. CraftWise ensures that subprocessors are contractually bound to data protection obligations meeting the requirements of Art. 28 GDPR.</p></div>
        <div class="legal-section"><h2>8. Third-country transfers</h2><p>The CraftWise app is generally designed for processing in EU regions where available and configured for the relevant infrastructure service. Nevertheless, third-country access or transfers cannot be excluded in all cases, in particular for global infrastructure services, support, push notifications, payment processing or optional integrations.</p><p>Where a third-country transfer is required, CraftWise ensures appropriate safeguards pursuant to Art. 44 et seq. GDPR, in particular adequacy decisions of the European Commission, EU Standard Contractual Clauses and supplementary technical or organisational measures where required.</p></div>
        <div class="legal-section"><h2>9. Personal data breaches</h2><p>CraftWise informs the controller without undue delay, no later than 48 hours after becoming aware of a personal data breach affecting personal data of the controller.</p><p>The notification includes, where available, the nature of the breach, categories and approximate number of affected data subjects and records, likely consequences, measures taken or proposed and a contact person. CraftWise documents personal data breaches internally and assists the controller where possible with its legal obligations.</p></div>
        <div class="legal-section"><h2>10. Assistance obligations</h2><p>CraftWise assists the controller where possible in fulfilling data subject rights under Art. 12 to 22 GDPR, data protection impact assessments under Art. 35 GDPR and consultations under Art. 36 GDPR, insofar as the requested information is available to CraftWise and concerns processing by CraftWise.</p><p>Requests from data subjects received directly by CraftWise are forwarded to the controller where allocation is possible. Legal assessment and response remain the responsibility of the controller.</p><p>Assistance exceeding the contractually owed platform functionality may be charged on a time and materials basis where provided in the main agreement or a separate agreement.</p></div>
        <div class="legal-section"><h2>11. Audit rights and evidence</h2><p>The controller may verify compliance with this DPA. CraftWise provides appropriate information and evidence upon request.</p><p>Audits are conducted upon prior notice with reasonable lead time, during normal business hours and with due regard to business secrets, security requirements and rights of other customers. CraftWise may offer equivalent evidence, document reviews, remote audits or certifications instead of an on-site audit where appropriate.</p><p>The controller bears the reasonable costs of an on-site audit unless the audit reveals a material data protection breach by CraftWise.</p></div>
        <div class="legal-section"><h2>12. Return, deletion and contract end</h2><p>The controller may export its data before contract end where export functions are provided.</p><p>After termination of the main agreement, CraftWise deletes or anonymises personal data of the controller within 30 days unless statutory retention obligations, legitimate interests or technical transition periods prevent this.</p><p>Data in backups is overwritten within regular backup cycles. Immediate deletion from backups is not technically possible in all cases. Backup data is not used for productive purposes until deletion and is protected appropriately.</p><p>The controller may request deletion confirmation in text form.</p></div>
        <div class="legal-section"><h2>13. Liability</h2><p>Liability is governed by the main agreement and statutory provisions, in particular Art. 82 GDPR. Where CraftWise is held liable due to an instruction of the controller or unlawful processing attributable to the controller, the controller indemnifies CraftWise internally against claims to the extent permitted by law.</p></div>
        <div class="legal-section"><h2>14. Final provisions</h2><p>Amendments and additions to this DPA require text form. In the event of conflicts between this DPA and the main agreement, this DPA prevails with regard to data protection obligations.</p><p>If any provision is invalid, the remaining provisions remain effective. German law applies.</p></div>
        <div class="legal-section"><h2>Annex 1 - Description of processing</h2><p>Subject matter: Provision and operation of the CraftWise SaaS platform for project management, time tracking, documents, communication, quote and invoice management and optional integrations.</p><p>Term: Term of the main agreement; deletion or anonymisation after termination in accordance with this DPA.</p><p>Nature of processing: Collection, recording, organisation, structuring, storage, adaptation, retrieval, consultation, use, disclosure by transmission within the platform, restriction, deletion and anonymisation.</p><p>Purposes: Contract performance, platform operation, support, security, error analysis, maintenance and improvement.</p><p>Data subjects: Employees and users of the controller, customers and contacts of the controller, project participants, subcontractors, suppliers and other persons whose data the controller processes in CraftWise.</p><p>Data categories: Master data, contact data, user and permission data, project and order data, appointment and calendar data, working time and absence data, documents, communication content, quote and invoice data, usage and security data.</p><p>Special categories of personal data: Not intended. Free text fields or absence data may contain special categories if entered by the controller. The controller controls content, legal basis and data minimisation.</p><p>Storage locations: App and core platform: in particular Firebase / Google Cloud in EU regions where available and configured. Public website: Hostinger. Individual technical services, push notifications, payment processing or optional integrations may involve processing outside the EU/EEA, in each case subject to appropriate safeguards.</p></div>
        <div class="legal-section"><h2>Annex 2 - Technical and organisational measures</h2><p><strong>Access, authorisation and authentication:</strong></p><ul><li>Roles and permissions based on least privilege.</li><li>Administrative access only for authorised persons.</li><li>Strong authentication for administrative access where available.</li><li>Logging of security-relevant events where technically available.</li><li>Protection against abusive access, e.g. through technical limits and monitoring.</li></ul><p><strong>Transmission and storage encryption:</strong></p><ul><li>TLS encryption for data transmission between client and server.</li><li>Encryption at rest by infrastructure providers used according to their standard security mechanisms.</li><li>Restricted access to systems and keys according to provider and permission concepts.</li></ul><p><strong>Availability, backup and recovery:</strong></p><ul><li>Use of backup, redundancy and recovery functions of infrastructure providers used.</li><li>Monitoring of availability, errors and security-relevant events according to an appropriate standard.</li><li>Incident response process for relevant security incidents.</li></ul><p><strong>Tenant separation:</strong></p><ul><li>Logical separation of customer data within the application and data storage.</li><li>Separation of production and test/development environments where technically and organisationally appropriate.</li><li>Productive data in test systems only where required and with appropriate safeguards.</li></ul><p><strong>Input and transfer control:</strong></p><ul><li>Timestamps and user attribution for relevant actions where technically implemented.</li><li>Limitation of data disclosures to what is necessary.</li><li>Secure interfaces to subprocessors and integration partners.</li></ul><p><strong>Organisational measures:</strong></p><ul><li>Confidentiality obligations for authorised persons.</li><li>Internal rules for access, permissions, incident handling and change management.</li><li>Awareness regarding data protection and information security.</li><li>Update and vulnerability management at reasonable intervals.</li></ul></div>
        <div class="legal-section"><h2>Annex 3 - Material subprocessors and recipients</h2><p>The following list contains material providers that may be relevant for operation, provision or billing of the platform. Additional providers may be added depending on activated functions.</p><p>Google Ireland Limited / Firebase / Google Cloud: App hosting, authentication, database, storage, technical platform services; region generally EU where available and configured; third-country transfer with appropriate safeguards where required.</p><p>Hostinger International Ltd.: Hosting of the public website and related technical website data; EU/EEA or infrastructure used by Hostinger; third-country transfer with appropriate safeguards where required.</p><p>Stripe Payments Europe, Limited: Payment processing, billing events, fraud prevention and compliance; EU/Ireland and potentially other countries according to Stripe structure; appropriate safeguards where required.</p><p>Apple Inc. / Apple Distribution International Ltd.: Push notifications for iOS devices via Apple Push Notification service; global; appropriate safeguards where required.</p><p>Google Ireland Limited / Google LLC: Push notifications for Android devices via Firebase Cloud Messaging; global; appropriate safeguards where required.</p><p>Optionally activated integrations: Microsoft, Google, Zoom, DATEV, sevdesk, lexoffice or comparable providers where activated by the customer; purpose and data scope depend on the respective integration.</p></div>
      `,
  },
];

export function getLegalContent(documentKey, locale) {
  return (
    LEGAL_CONTENT.find((item) => item.key === documentKey && item.locale === locale) ||
    null
  );
}
